### ISSUE TITLE
Descrizione

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/nepero#1]
![es3_47](https://cloud.githubusercontent.com/assets/3002194/14016986/1e7b5c76-f1c4-11e5-9e1b-78e666a8751c.png)

**Comment by FabioZTessitore** [comment]
a questo punto non dovrebbe essere difficile fare il punto C

**Comment by FabioZTessitore** [comment]
anche per la x vale lo stesso discorso del denominatore. è inutile calcolare ogni volta

**Comment by Teodoro777** [comment]
Il programma ora va bene, bisogna cambiare ora la condizione del ciclo perché non c'è più e ma e^x

**Comment by FabioZTessitore** [comment]
ok, cia siamo

riguardo alla condizione di fine ciclo ...
invece di fare la differenza tra il valore calcolato e il valore vero, bisogna valutare la differenza tra il vecchio valore calcolato e il nuovo valore calcolato. Quando questa differenza è abbastanza piccola non vale più la pena aggiungere termini
