### ISSUE TITLE
Fattoriale

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/nepero#2]
Vedi Issue #1 
Calcolare il fattoriale di un numero inserito (parte a della descrizione)

**Comment by Teodoro777** [comment]
Ho fatto il procedimento a carta e penna, sembra filare... Vedo di aggiustare il codice

**Comment by FabioZTessitore** [comment]
scusa ma lo hai provato? esce sempre 0

**Comment by Teodoro777** [comment]
Si infatti ho detto "vedo di aggiustare il codice"

**Comment by Teodoro777** [comment]
Ho risolto eseguendo le moltiplicazioni due e due..

2016-03-25 16:24 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
ora funziona, ma è inutilmente complesso. Perché moltiplicare due numeri per ogni ciclo e avanzare di due?

**Comment by Teodoro777** [comment]
Ahah e che ne so certe volte mi escono le soluzioni più complesse

2016-03-25 20:05 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
hai aggiustato il tiro. Ora mi spieghi quella variabile `i`

**Comment by Teodoro777** [comment]
Ahah assolutamente a niente
