### ISSUE TITLE
exp

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/nepero#3]
Passiamo alla parte b. Bisogna approssimare il valore di e con la formula data.
Cerca di andare per gradi. All'inizio consideriamo solo i primi tre elementi della somma.

**Comment by Teodoro777** [comment]
Il programma è ovviamente da ritoccare

**Comment by FabioZTessitore** [comment]
per n = 1, 2, 3 mi trovo.
n = 4 no

**Comment by Teodoro777** [comment]
Ahah l'ho verificato anche io.. Ora cerco il bug

Il sabato 26 marzo 2016, Fabio Z Tessitore <notifications@github.com> ha
scritto:

**Comment by Teodoro777** [comment]
Debug ultimato ahah facilissimo, dovevo riportare la variabile fat ad 1
come NON avevo fatto in fattoriale.c visto che non riutilizzavo quella
variabile

Il sabato 26 marzo 2016, Teodoro Coluccio <teodoro.coluccio@gmail.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
ok, per il momento va bene, poi però ne dobbiamo riparlare
