### ISSUE TITLE
quanti termini?

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/nepero#4]
come facciamo a sapere quanti termini della serie dobbiamo prendere?

**Comment by Teodoro777** [comment]
Eh ne dovremmo prendere infiniti, ma nel linguaggio dobbiamo mettere il
numero massimo che permette..

Il sabato 26 marzo 2016, Fabio Z Tessitore <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
Non proprio ma quasi.
La prima possibilità (che hai già fatto) è quella di scegliere sin dall'inizio il numero di termini. Ovviamente non è una soluzione soddisfacente.

La seconda possibilità potrebbe essere quella di misurare la differenza tra il valore che hai calcolato e quello vero e fermarsi quando diventa più piccola di un valore prestabilito. Non è ancora la cosa migliore da fare ma ... fallo!

**Comment by Teodoro777** [comment]
Ok e quel valore prestabilito lo scelgo io?

Inviato da iPad

**Comment by FabioZTessitore** [comment]
certo

**Comment by Teodoro777** [comment]
Il programma funziona bene, non so se il risultato sia proprio esatto..

**Comment by FabioZTessitore** [comment]
la differenza tra valore "esatto" e valore calcolato dovrebbe essere calcolata in valore assoluto
