### ISSUE TITLE
compilazione

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/nepero#5]
visto che hai usato la libreria matematica, mi dici come hai compilato?

**Comment by Teodoro777** [comment]
Solito "gcc new_exp.c"

Inviato da iPad

**Comment by FabioZTessitore** [comment]
Non va bene.

# Compilazione con gcc
Quando effettui la compilazione dovresti usare alcune opzioni:
-c   (compila soltanto)
-ansi    (solo C standard ANSI)
-Wall    (avvisa per tutto)
-pedantic  (fornisce più avvisi, da usare insieme a -ansi)
```bash
$ gcc -c -ansi -Wall -pedantic new_exp.c -o new_exp.o
```
Infine puoi collegare le librerie (quella standard viene collegata automaticamente, mentre quella matematica va indicata)
```bash
$ gcc -lm new_exp.o -o new_exp
```

**Comment by FabioZTessitore** [comment]
# Compilazione con make
Dovresti anche iniziare ad usare make. In questo caso si tratta di settare alcune variabili di ambiente.
La variabile `CFLAGS` contiene le opzioni di compilazione, mentre `LDFLAGS` contiene le librerie da collegare.
```bash
$ make CFLAGS="-Wall -ansi -pedantic" LDFLAGS="-lm" new_exp
```
(*Nota bene*: non viene indicato il nome del file sorgente, ma il nome dell'eseguibile. make va a cercare il file new_exp.c)
