### ISSUE TITLE
costanti matematiche

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/nepero#6]
alle variabili dichiarate come double dovrebbero essere assegnati valori double ...

invece `num` che vale `0.00001` potrebbe essere riscritta come `num = 1.E-5` che significa `1.0 x 10^-5`

**Comment by Teodoro777** [comment]
Fatto

**Comment by FabioZTessitore** [comment]
le righe 16, 17 e 21 non ti piacevano?
